
const DEMO_REPORTS_KEY='econexus_reports_v2';
const demoReports=[
{id:'ENX-2026-004821',type:'Disposal',category:'Plastic',location:'Sector 12 Market, Near Bus Stand',severity:'Medium',status:'In Progress',date:'2026-08-29',description:'Loose plastic waste piling up behind the vegetable stalls.'},
{id:'ENX-2026-004798',type:'Sanitation',category:'Overflowing garbage',location:'Hostel Block C, GreenTech Institute',severity:'High',status:'Assigned',date:'2026-08-27',description:'Community bin overflowing for two days near the mess hall.'},
{id:'ENX-2026-004750',type:'Sanitation',category:'Blocked drain',location:'MG Road, Ward 7',severity:'Critical',status:'Resolved',date:'2026-08-20',description:'Stormwater drain blocked with construction debris, water pooling on the road.'},
{id:'ENX-2026-004702',type:'Disposal',category:'E-waste',location:'Campus Electronics Lab',severity:'Low',status:'Resolved',date:'2026-08-14',description:'Discarded circuit boards and batteries left outside the lab.'}
];
function getReports(){try{return JSON.parse(localStorage.getItem(DEMO_REPORTS_KEY))||demoReports}catch{return demoReports}}
function saveReports(r){localStorage.setItem(DEMO_REPORTS_KEY,JSON.stringify(r))}
function toast(msg){const t=document.querySelector('#toast');if(!t)return;t.textContent=msg;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),2400)}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function initNav(){const current=location.pathname.split('/').pop()||'index.html';document.querySelectorAll('nav a').forEach(a=>{if(a.getAttribute('href')===current)a.classList.add('active')})}
function preview(input,target){const f=input.files?.[0];const img=document.getElementById(target);if(!f||!img)return;img.src=URL.createObjectURL(f);img.style.display='block'}
function getRealGPS(){return new Promise((resolve,reject)=>{if(!navigator.geolocation)return reject(new Error('Geolocation is not supported by this browser.'));navigator.geolocation.getCurrentPosition(resolve,reject,{enableHighAccuracy:true,timeout:15000,maximumAge:0})})}
async function useGPS(target='location',coordsTarget='gpsResult'){const btn=event?.currentTarget;if(btn){btn.disabled=true;btn.textContent='Getting precise location…'}try{const p=await getRealGPS();const text=`Latitude: ${p.coords.latitude.toFixed(6)}, Longitude: ${p.coords.longitude.toFixed(6)} • Accuracy: ${Math.round(p.coords.accuracy)} m`;const input=document.getElementById(target);if(input)input.value=`${p.coords.latitude.toFixed(6)}, ${p.coords.longitude.toFixed(6)}`;const box=document.getElementById(coordsTarget);if(box)box.textContent=text;const pin=document.getElementById('realPin');if(pin){pin.style.left=(20+(Math.abs(p.coords.longitude)%60))%80+'%';pin.style.top=(20+(Math.abs(p.coords.latitude)%55))%65+'%'}toast('Real device location captured');}catch(e){const box=document.getElementById(coordsTarget);if(box)box.textContent=e.code===1?'Location permission was denied. Enter the location manually.':'Unable to obtain location. Check browser location permission and try again.';toast('Could not capture location');}finally{if(btn){btn.disabled=false;btn.textContent='📍 Use my real GPS'}}}
function submitReport(form,type){const fd=new FormData(form);const r=getReports();const id='ENX-2026-'+String(4822+r.length).padStart(6,'0');const report={id,type,category:fd.get('category')||fd.get('issue')||'Other',location:fd.get('location')||'Location not provided',severity:fd.get('severity')||'Medium',status:'Reported',date:new Date().toISOString().slice(0,10),description:fd.get('description')||''};r.unshift(report);saveReports(r);localStorage.setItem('econexus_last_report',id);toast(`Report submitted: ${id}`);setTimeout(()=>location.href='tracking.html?id='+encodeURIComponent(id),700)}
function analyzeWaste(){const file=document.getElementById('aiFile')?.files?.[0];if(!file){toast('Choose a waste photo first');return}const name=file.name.toLowerCase();let x={object:'Mixed dry material',category:'Dry / Recyclable',bin:'BLUE',confidence:91,reason:'Likely recyclable dry material. Keep it clean and dry.',action:'Separate clean recyclable material from wet waste.'};if(/food|fruit|vegetable|wet|organic/.test(name))x={object:'Organic waste',category:'Wet / Organic',bin:'GREEN',confidence:94,reason:'Likely biodegradable organic waste.',action:'Place in the wet/organic stream and avoid mixing with plastics.'};else if(/battery|chemical|medical|ewaste|e-waste/.test(name))x={object:'Special / E-waste',category:'Hazardous / Special',bin:'RED',confidence:88,reason:'Special handling is required. Do not mix with regular waste.',action:'Use an authorized collection point and keep hazardous items separate.'};else if(/plastic|bottle|pet/.test(name))x={object:'PET Plastic Bottle',category:'Plastic / Recyclable',bin:'BLUE',confidence:96,reason:'Likely recyclable PET plastic. Empty and keep it clean and dry.',action:'Empty → rinse if appropriate → separate → send to recyclable collection.'};document.getElementById('result').innerHTML=`<div class="eyebrow" style="color:#baf36a">AI CLASSIFICATION • DEMO</div><h2>${esc(x.object)}</h2><p>${esc(x.reason)}</p><div class="bar"><i style="width:${x.confidence}%"></i></div><p>${x.confidence}% suggested confidence</p><div class="card" style="margin-top:18px;background:#0d3428;border-color:#426957"><small>RECOMMENDED STREAM</small><h2 style="color:#baf36a">${x.bin}</h2><p>${esc(x.action)}</p><span class="badge">Prototype AI result</span></div>`;localStorage.setItem('econexus_last_ai',JSON.stringify(x));toast('Waste analysis complete')}
function renderTracking(){const el=document.getElementById('trackingList');if(!el)return;const reports=getReports();const id=new URLSearchParams(location.search).get('id');const shown=id?reports.filter(r=>r.id===id):reports;el.innerHTML=shown.length?shown.map(r=>`<div class="card"><div class="eyebrow">${esc(r.type)} REPORT</div><h3>${esc(r.id)}</h3><p><b>${esc(r.category)}</b> • ${esc(r.location)}</p><span class="status">${esc(r.status)}</span><p>${esc(r.description)}</p><div class="timeline"><div class="timeline-item active"><span class="circle">✓</span><div><b>Reported</b><br><small>Evidence and location captured</small></div></div><div class="timeline-item ${['Assigned','In Progress','Resolved'].includes(r.status)?'active':''}"><span class="circle">2</span><div><b>Assigned</b><br><small>Nearest eligible team notified</small></div></div><div class="timeline-item ${['In Progress','Resolved'].includes(r.status)?'active':''}"><span class="circle">3</span><div><b>In Progress</b><br><small>Action underway</small></div></div><div class="timeline-item ${r.status==='Resolved'?'active':''}"><span class="circle">4</span><div><b>Resolved</b><br><small>Closure recorded</small></div></div></div></div>`).join(''):'<div class="card empty">No reports found.</div>'}
function renderAdmin(){const body=document.getElementById('adminRows');if(!body)return;const reports=getReports();body.innerHTML=reports.map((r,i)=>`<tr><td>${esc(r.id)}</td><td>${esc(r.type)} / ${esc(r.category)}</td><td>${esc(r.location)}</td><td>${esc(r.severity)}</td><td><select data-i="${i}" class="adminStatus"><option ${r.status==='Reported'?'selected':''}>Reported</option><option ${r.status==='Assigned'?'selected':''}>Assigned</option><option ${r.status==='In Progress'?'selected':''}>In Progress</option><option ${r.status==='Resolved'?'selected':''}>Resolved</option></select></td></tr>`).join('');document.querySelectorAll('.adminStatus').forEach(s=>s.onchange=()=>{const r=getReports();r[+s.dataset.i].status=s.value;saveReports(r);renderAdmin();toast('Report status updated')});document.getElementById('adminTotal').textContent=reports.length;document.getElementById('adminOpen').textContent=reports.filter(x=>x.status!=='Resolved').length;document.getElementById('adminProgress').textContent=reports.filter(x=>x.status==='In Progress').length;document.getElementById('adminResolved').textContent=reports.filter(x=>x.status==='Resolved').length}
function initDashboard(){const r=getReports();const e=id=>document.getElementById(id);if(!e('reportCount'))return;e('reportCount').textContent=r.length;e('resolvedCount').textContent=r.filter(x=>x.status==='Resolved').length;e('ecoPoints').textContent=420+r.length*20;e('diverted').textContent=(23+r.length*1.7).toFixed(1)+' kg';const a=e('recentActivity');a.innerHTML=r.slice(0,4).map(x=>`<div class="timeline-item active"><span class="circle">✓</span><div><b>${esc(x.id)}</b><br><small>${esc(x.status)} • ${esc(x.category)}</small></div></div>`).join('')}
function saveIdea(name){let a=JSON.parse(localStorage.getItem('econexus_saved_ideas')||'[]');if(!a.includes(name))a.push(name);localStorage.setItem('econexus_saved_ideas',JSON.stringify(a));toast('Idea saved to your T2T library')}
document.addEventListener('DOMContentLoaded',()=>{initNav();renderTracking();renderAdmin();initDashboard();const form=document.querySelector('[data-report-form]');if(form)form.addEventListener('submit',e=>{e.preventDefault();submitReport(form,form.dataset.type)});document.querySelectorAll('.save-idea').forEach(b=>b.addEventListener('click',()=>saveIdea(b.dataset.idea)))})
